---
# This is a template for publishing Storybook to Chromatic
name: _storybook-publish.yaml
on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        description: The directory where Storybook should be published from
        type: string
      node-version:
        required: false
        default: '20'
        description: The version of Node.js to use
        type: string
    secrets:
      PROJECT_TOKEN:
        required: true
        description: Chromatic project token for publishing
jobs:
  publish:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: npm
          cache-dependency-path: package-lock.json
      - name: Cache
        id: cache-modules
        uses: actions/cache@v1
        with:
          path: ./node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        # if: steps.cache-modules.outputs.cache-hit != 'true'
        run: |
          npm install
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.PROJECT_TOKEN }}
          exitZeroOnChanges: true
          workingDir: ${{ inputs.working-directory }}
