---
name: apps.idioma.storybook.publish
on:
  push:
    branches:
      - '**'  # This excludes tags
    paths: [apps/idioma/**]
defaults:
  run:
    working-directory: apps/idioma
jobs:
  test-compile:
    uses: ./.github/workflows/_storybook-publish.yaml
    secrets:
      PROJECT_TOKEN: ${{ secrets.IDIOMA_CHROMATIC_PROJECT }}
    with:
      working-directory: apps/idioma
