name: apps.site.test-compile.production

on:
  push:
    branches:
      - production
    paths:
      - "apps/template-react/**"

defaults:
  run:
    working-directory: apps/template-react

jobs:
  test-compile:
    uses: ./.github/workflows/_template.apps.compile.yaml
    with:
      working-directory: apps/template-react
      GRAPHQL_ENDPOINT: ${{ env.GRAPHQL_ENDPOINT }} 
