---
name: apps.example.storybook.publish
on:
  push:
    branches:
      - '**'  # This excludes tags
    paths: [apps/example/**]
defaults:
  run:
    working-directory: apps/example
jobs:
  test-compile:
    uses: ./.github/workflows/_storybook-publish.yaml
    secrets:
      PROJECT_TOKEN: ${{ secrets.TEMPLATE_REACT_CHROMATIC_PROJECT }}
    with:
      working-directory: apps/example
