name: packages.design-system.storybook.publish
  
on:
  push:
    paths:
      - "packages/design-system/**"

defaults:
  run:
    working-directory: packages/design-system

jobs:
  test-compile:
    uses: ./.github/workflows/_template.storybook.publish.yaml
    secrets:
      inherit
    with:
      working-directory: packages/design-system
